### ISSUE TITLE
Замечания к заданию #4

### ISSUE THREAD

**Issue by alexey-kozlenkov** [yaliza/bsu-practise-2018#3]
0. Почему `photoPosts` не замкнут в модуле, как все остальное?
1. Что за hidden свойство? Оно отсутствует во всех элементах `photoPosts` массива.
```
let resultPosts = photoPosts.filter(function (currentElement) {
  return !currentElement.isHidden;
});
```
2. Используйте strict-type сравнения === и !== (`return currentElement.author == filterConfig.author;`, `filterConfig != undefined`)

3. Здесь очень напрашивается метод `.find()` у массива вместо `.filter(...)[0]`
```
function getPhotoPost(findId) {
  return photoPosts.filter(function (currentElement) {
    return currentElement.id == findId;
  })[0];
}
```
4. Лучше всегда использовать фигурные скобки
```
if (photoPost.id != undefined || photoPost.author != undefined || photoPost.createdAt != undefined)
  return false;
```
5. Метод `editPhotoPost`
    1. (В целом) Не стоит изменять входные параметры функции, старайтесь всегда использовать параметры только в read mode.
    2. Возможно, проще один раз найти элемент в массиве `photoPosts`, скопировать его данные в новый объект (чтобы не изменять элемент массива) (погуглите, как лучше всего это сделать :)), потом в этот объект скопировать все данные из параметра. Затем провалидировать и положить в массив.

В общем и целом все хорошо.
Большой плюс за активное использование функций Array.

**Comment by yaliza** [comment]
Исправлено.
